standard = "2008"

project.files = ["hdl/**/*.vhd"]

[libraries]
vunit_lib.files = [
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/dict_pkg-body.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/dict_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/queue_pool_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/integer_vector_ptr_pool_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/data_types_private_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/event_private_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/dict_pkg-2008p.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/codec-2008p.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/string_ptr_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/integer_vector_ptr_pkg-body-2002p.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/integer_vector_ptr_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/types.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/event_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/integer_array_pkg-body.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/queue_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/codec_builder-2008p.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/queue_pkg-2008p.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/id_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/codec_builder.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/string_ptr_pool_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/event_common_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/integer_array_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/data_types_context.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/codec.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/queue_pkg-body.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/byte_vector_ptr_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/api/external_string_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/api/external_integer_vector_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/logging/src/location_pkg-body-2008m.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/logging/src/log_deprecated_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/logging/src/logger_pkg-body.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/logging/src/log_handler_pkg-body.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/logging/src/ansi_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/logging/src/location_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/logging/src/print_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/logging/src/logger_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/logging/src/file_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/logging/src/print_pkg-body.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/logging/src/log_handler_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/logging/src/log_levels_pkg-body.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/logging/src/log_levels_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/vunit_run_context.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/vunit_context.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/core/src/core_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/core/src/stop_body_2008p.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/core/src/stop_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/string_ops/src/string_ops.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/check/src/checker_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/check/src/checker_pkg-body.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/check/src/check.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/check/src/check_api.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/check/src/check_deprecated_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/dictionary/src/dictionary.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/run/src/runner_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/run/src/run_deprecated_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/run/src/run_types.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/run/src/run_api.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/run/src/run.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/path/src/path.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/com/src/com_deprecated.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/com/src/com.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/com/src/com_context.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/com/src/com_string.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/com/src/com_support.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/com/src/com_debug_codec_builder.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/com/src/com_api.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/com/src/com_messenger.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/com/src/com_types.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/com/src/com_common.vhd",
]
vunit_lib.is_third_party = true

osvvm.files = [
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/ScoreboardPkg_slv.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/TextUtilPkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/RandomProcedurePkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/CoveragePkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/RandomBasePkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/MessagePkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/ScoreboardPkg_int.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/OsvvmGlobalPkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/SortListPkg_int.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/NamePkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/TbUtilPkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/RandomPkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/ResizePkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/ScoreboardGenericPkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/NameStorePkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/MessageListPkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/TranscriptPkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/ReportPkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/VendorCovApiPkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/OsvvmContext.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/ResolutionPkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/AlertLogPkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/MemoryPkg.vhd",
]
osvvm.is_third_party = true

uvvm_util.files = [
  "../../opt/uvvm/uvvm_util/src/types_pkg.vhd",
  "../../opt/uvvm/uvvm_util/src/adaptations_pkg.vhd",
  "../../opt/uvvm/uvvm_util/src/string_methods_pkg.vhd",
  "../../opt/uvvm/uvvm_util/src/protected_types_pkg.vhd",
  "../../opt/uvvm/uvvm_util/src/global_signals_and_shared_variables_pkg.vhd",
  "../../opt/uvvm/uvvm_util/src/hierarchy_linked_list_pkg.vhd",
  "../../opt/uvvm/uvvm_util/src/alert_hierarchy_pkg.vhd",
  "../../opt/uvvm/uvvm_util/src/license_pkg.vhd",
  "../../opt/uvvm/uvvm_util/src/methods_pkg.vhd",
  "../../opt/uvvm/uvvm_util/src/bfm_common_pkg.vhd",
  "../../opt/uvvm/uvvm_util/src/generic_queue_pkg.vhd",
  "../../opt/uvvm/uvvm_util/src/data_queue_pkg.vhd",
  "../../opt/uvvm/uvvm_util/src/data_fifo_pkg.vhd",
  "../../opt/uvvm/uvvm_util/src/data_stack_pkg.vhd",
  "../../opt/uvvm/uvvm_util/src/rand_pkg.vhd",
  "../../opt/uvvm/uvvm_util/src/func_cov_pkg.vhd",
  "../../opt/uvvm/uvvm_util/src/uvvm_util_context.vhd",
]
uvvm_util.is_third_party = true

uvvm_vvc_framework.files = [
  "../../opt/uvvm/uvvm_vvc_framework/src/ti_protected_types_pkg.vhd",
  "../../opt/uvvm/uvvm_vvc_framework/src/ti_vvc_framework_support_pkg.vhd",
  "../../opt/uvvm/uvvm_vvc_framework/src/ti_generic_queue_pkg.vhd",
  "../../opt/uvvm/uvvm_vvc_framework/src/ti_data_queue_pkg.vhd",
  "../../opt/uvvm/uvvm_vvc_framework/src/ti_data_fifo_pkg.vhd",
  "../../opt/uvvm/uvvm_vvc_framework/src/ti_data_stack_pkg.vhd",
  "../../opt/uvvm/uvvm_vvc_framework/src/ti_uvvm_engine.vhd",
  "../../opt/uvvm/uvvm_vvc_framework/src/ti_vvc_framework_context.vhd",
]
uvvm_vvc_framework.is_third_party = true

bitvis_vip_scoreboard.files = [
  "../../opt/uvvm/bitvis_vip_scoreboard/src/generic_sb_support_pkg.vhd",
  "../../opt/uvvm/bitvis_vip_scoreboard/src/generic_sb_pkg.vhd",
  "../../opt/uvvm/bitvis_vip_scoreboard/src/predefined_sb.vhd",
]
bitvis_vip_scoreboard.is_third_party = true

bitvis_uart.files = [
  "../../opt/uvvm/bitvis_uart/src/uart_pkg.vhd",
  "../../opt/uvvm/bitvis_uart/src/uart_pif_pkg.vhd",
  "../../opt/uvvm/bitvis_uart/src/uart_pif.vhd",
  "../../opt/uvvm/bitvis_uart/src/uart_core.vhd",
  "../../opt/uvvm/bitvis_uart/src/uart.vhd",
]
bitvis_uart.is_third_party = true

bitvis_vip_uart.files = [
  "../../opt/uvvm/bitvis_vip_uart/src/uart_bfm_pkg.vhd",
  "../../opt/uvvm/bitvis_vip_uart/src/transaction_pkg.vhd",
  "../../opt/uvvm/bitvis_vip_uart/src/vvc_cmd_pkg.vhd",
  "../../opt/uvvm/bitvis_vip_uart/src/monitor_cmd_pkg.vhd",
  "../../opt/uvvm/uvvm_vvc_framework/src_target_dependent/td_target_support_pkg.vhd",
  "../../opt/uvvm/uvvm_vvc_framework/src_target_dependent/td_vvc_framework_common_methods_pkg.vhd",
  "../../opt/uvvm/bitvis_vip_uart/src/vvc_sb_pkg.vhd",
  "../../opt/uvvm/bitvis_vip_uart/src/vvc_methods_pkg.vhd",
  "../../opt/uvvm/uvvm_vvc_framework/src_target_dependent/td_queue_pkg.vhd",
  "../../opt/uvvm/uvvm_vvc_framework/src_target_dependent/td_vvc_entity_support_pkg.vhd",
  "../../opt/uvvm/bitvis_vip_uart/src/uart_rx_vvc.vhd",
  "../../opt/uvvm/bitvis_vip_uart/src/uart_tx_vvc.vhd",
  "../../opt/uvvm/bitvis_vip_uart/src/uart_vvc.vhd",
  "../../opt/uvvm/bitvis_vip_uart/src/uart_monitor.vhd",
  "../../opt/uvvm/bitvis_vip_uart/src/vvc_context.vhd",
]
bitvis_vip_uart.is_third_party = true

bitvis_vip_clock_generator.files = [
  "../../opt/uvvm/bitvis_vip_clock_generator/src/vvc_cmd_pkg.vhd",
  "../../opt/uvvm/uvvm_vvc_framework/src_target_dependent/td_target_support_pkg.vhd",
  "../../opt/uvvm/uvvm_vvc_framework/src_target_dependent/td_vvc_framework_common_methods_pkg.vhd",
  "../../opt/uvvm/bitvis_vip_clock_generator/src/vvc_methods_pkg.vhd",
  "../../opt/uvvm/uvvm_vvc_framework/src_target_dependent/td_queue_pkg.vhd",
  "../../opt/uvvm/uvvm_vvc_framework/src_target_dependent/td_vvc_entity_support_pkg.vhd",
  "../../opt/uvvm/bitvis_vip_clock_generator/src/clock_generator_vvc.vhd",
  "../../opt/uvvm/bitvis_vip_clock_generator/src/vvc_context.vhd",
]
bitvis_vip_clock_generator.is_third_party = true

main.files = [
  "hdl/uvvm-demo/uvvm_logger_tb.vhd",
  "hdl/osvvm-demo/osvvm_logger_tb.vhd",
]

[diagnostics]
enable = false
style_checks = false
warnings = false
