standard = "2008"
[libraries]
vunit_lib.files = [
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/dict_pkg-body.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/dict_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/queue_pool_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/integer_vector_ptr_pool_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/data_types_private_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/event_private_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/dict_pkg-2008p.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/codec-2008p.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/string_ptr_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/integer_vector_ptr_pkg-body-2002p.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/integer_vector_ptr_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/types.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/event_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/integer_array_pkg-body.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/queue_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/codec_builder-2008p.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/queue_pkg-2008p.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/id_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/codec_builder.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/string_ptr_pool_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/event_common_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/integer_array_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/data_types_context.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/codec.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/queue_pkg-body.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/byte_vector_ptr_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/api/external_string_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/data_types/src/api/external_integer_vector_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/logging/src/location_pkg-body-2008m.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/logging/src/log_deprecated_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/logging/src/logger_pkg-body.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/logging/src/log_handler_pkg-body.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/logging/src/ansi_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/logging/src/location_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/logging/src/print_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/logging/src/logger_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/logging/src/file_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/logging/src/print_pkg-body.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/logging/src/log_handler_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/logging/src/log_levels_pkg-body.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/logging/src/log_levels_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/vunit_run_context.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/vunit_context.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/core/src/core_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/core/src/stop_body_2008p.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/core/src/stop_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/string_ops/src/string_ops.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/check/src/checker_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/check/src/checker_pkg-body.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/check/src/check.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/check/src/check_api.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/check/src/check_deprecated_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/dictionary/src/dictionary.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/run/src/runner_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/run/src/run_deprecated_pkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/run/src/run_types.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/run/src/run_api.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/run/src/run.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/path/src/path.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/com/src/com_deprecated.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/com/src/com.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/com/src/com_context.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/com/src/com_string.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/com/src/com_support.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/com/src/com_debug_codec_builder.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/com/src/com_api.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/com/src/com_messenger.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/com/src/com_types.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/com/src/com_common.vhd",
]
osvvm.files = [
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/ScoreboardPkg_slv.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/TextUtilPkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/RandomProcedurePkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/CoveragePkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/RandomBasePkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/MessagePkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/ScoreboardPkg_int.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/OsvvmGlobalPkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/SortListPkg_int.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/NamePkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/TbUtilPkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/RandomPkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/ResizePkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/ScoreboardGenericPkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/NameStorePkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/MessageListPkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/TranscriptPkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/ReportPkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/VendorCovApiPkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/OsvvmContext.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/ResolutionPkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/AlertLogPkg.vhd",
  "../../usr/local/lib/python3.12/dist-packages/vunit/vhdl/osvvm/MemoryPkg.vhd",
]
[lint]
unused = 'error'
unnecessary_work_library = false